#include "timer.h"
#include "led.h"
#include "usart.h"
#include "ultrasonic.h"
#include "sys.h"
void motor_init(void);
void UP(void);
void DOWN(void);
void EN_motor(void);
void DIS_motor(void);
void stop_motor(void);
